#!/bin/zsh -feu

# create the content:
# git-tsort -s > $tmpfile
set -x
readonly blob_hash=$(git-tsort -s | git hash-object --stdin -w)
# check it didn't fail.

# check:
git cat-file -p $blob_hash

MODE=100644
FILENAME=hierarchy
branch="_hierarchy"

readonly tree_hash=$(echo "$MODE blob $blob_hash\t$FILENAME"| git mktree)
# |git update-index  --index-info

commit=$(echo "new hierarchy" | git commit-tree $tree_hash)

git branch -f $branch $commit

