#!/bin/zsh -feu

source /usr/share/git-hierarchy/functions.sh
GIT_DIR=$(git_dir)


# success
if test -f "$GIT_DIR/.rebasing-segment"; then
    git-reset-segment $(cat "$GIT_DIR/.rebasing-segment")
fi

# success, so remove it:
# fixme: only if they are ours!

: ${file=$GIT_DIR/hooks/post-rebase}

remove_symlink_to $GIT_DIR/hooks/post-rebase /usr/share/git-hierarchy/git-rebase-complete
remove_symlink_to $GIT_DIR/hooks/post-abort /usr/share/git-hierarchy/git-rebase-abort

