#!/bin/bash -eu

source /usr/share/git-hierarchy/functions.sh
GIT_DIR=$(git_dir)


# success
if test -f "$GIT_DIR/.rebasing-segment"; then
    git-reset-segment $(cat "$GIT_DIR/.rebasing-segment")
fi

# success, so remove it:
rm -fv $GIT_DIR/hooks/post-rebase
